[package]
name = "uefi-bootloader"
version = "0.1.0"
authors = ["Yuya Fujita <bh20.us178fujita@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

